context:
  name: pytranskit
  version: "0.3.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pytranskit-${{ version }}.tar.gz
  sha256: 7c30deb7d6515944a4a5048574be4860217dba9874725e9c2a8b40da2f25712d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python =${{ python_min }}
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - matplotlib-base
    - numpy
    - scikit-image
    - scipy
    - six

tests:
  - python:
      imports:
        - pytranskit
      pip_check: true

about:
  summary: Python transport based signal processing toolkit.
  license: GPL-3.0-only
  license_file: LICENSE
  homepage: https://github.com/rohdelab/PyTransKit

extra:
  recipe-maintainers:
    - danielnachun
    - goanpeca
