context:
  name: pytranskit
  version: "0.3.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pytranskit-${{ version }}.tar.gz
  sha256: b004c18f9a31a32ebba3670b2f4ba99c780da8e48c5a4d13a633a874fe8130b1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python =${{ python_min }}
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - matplotlib-base
    - numpy
    - scikit-image
    - scipy
    - six

tests:
  - python:
      imports:
        - pytranskit
      pip_check: true

about:
  summary: Python transport based signal processing toolkit.
  license: GPL-3.0-only
  license_file: LICENSE
  homepage: https://github.com/rohdelab/PyTransKit

extra:
  recipe-maintainers:
    - danielnachun
    - goanpeca
